import App from './App.svelte';

const pics = [
	{"c": 8, "w": 413, "p": "jazzjackrabbit", "t":"Jazz Jackrabbit", "d": "is a platform game developed and  released in 1994 by Epic Games. Jazz was coded by Arjan Brussee and designed by Cliff Bleszinski", "m": ["072t"], "s": ["ts","fe","ps","hl"]},
	{"c": 2, "w": 470, "p": "zerowarningpolicy", "t":"zero-warning policy", "d": "is a software development approach when you to treat warnings as errors", "m": ["077d"], "s": ["bb","hd"]},
	{"c": 11, "w": 384, "p": "circularbuffer", "t":"Circular Buffer", "d": "is a data structure that uses a single, fixed-size buffer as if it were connected end-to-end.", "m": ["079t"], "s": ["tm","fe","ps","hl"], "b": 1},
	{"c": 3, "w": 720, "p": "lowpoly", "t":"Low Poly", "d": "is a polygon mesh in 3D computer graphics that has a relatively small number of polygons. Low poly meshes occur in real-time games", "m": ["077d"], "s": ["tb","fm","pt","hd"]},
	{"c": 9, "w": 432, "p": "lookofdisapproval", "t":"look_of_disapproval", "d": "Unicode smile and a reddit meme started by the user look_of_disapproval, who often post ಠ_ಠ messages", "m": ["078g"], "s": ["bb","hd"], "b": 1},
	{"c": 11, "w": 754, "p": "flac", "t":"FLAC", "d": "Free Lossless Audio Codec is an audio coding format for lossless compression of digital audio. Development of it was started in 2000 by Josh Coalson", "m": ["076v"], "s": ["ts","fe","ps","hl"], "b": 1},
	{"c": 12, "w": 576, "p": "condensation", "t":"ConDensAtion", "d": "Conditional Density Propagation is a computer vision algorithm, it was described by Isard and Andrew Blake in a publicated in 1998", "m": ["068a"], "s": ["ts","fe","ps","hd"], "b": 1},
	{"c": 11, "w": 720, "p": "guid", "t":"Globally Unique ID", "d": "is a special type of identifier used in software applications in order to provide a reference number which is unique in any context for creating unique keys in a database.", "m": ["074r"], "s": ["ph"]},
	{"c": 12, "w": 576, "p": "bayestheorem", "t":"Bayes' theorem", "d": "named after the Reverend Thomas Bayes(1701-1761), describes the probability of an event, based on prior knowledge of conditions that might be related to the event", "m": ["065s"], "s": ["ts","fe","ps","hr"]},
	{"c": 2, "w": 576, "p": "404", "t":"404", "d": "is most known HTTP code indicates that resource not found or document doesn't exist", "m": ["016k"], "s": ["ps"], "b": 1},
	{"c": 8, "w": 415, "p": "warcraft", "t":"Warcraft", "d": "Orcs & Humans is a real-time strategy game (RTS), it's first game in Warcraft series, it was for MS-DOS in North America on 23 November 1994 by Blizzard Entertainment,", "m": ["076v"], "s": ["ts","fm","ps","hl"]},
	{"c": 2, "w": 507, "p": "watchdog", "t":"Watchdog", "d": "timer is an electronic or software timer that is used to detect and recover from computer malfunctions", "m": ["035s"], "s": ["tb","fm","pt","hl"]},
	{"c": 10, "w": 768, "p": "container", "t":"Container", "d": "is an isolated, lightweight silo for running an application on the host operating system. Containers build on top of the host operating system's kernel, and contain only apps and some lightweight operating system APIs", "m": ["075k"], "s": ["tb","fe","ps","hr"], "b": 1},
	{"c": 7, "w": 527, "p": "volatility", "t":"Volatility", "d": " is a statistical measure that captures the size of moves seen by an investment, like a share, moving up or down over a set period", "m": ["054k"], "s": ["br","hd"]},
	{"c": 7, "w": 576, "p": "slss", "t":"SLSS", "d": "Social Live Stream Services (SLSS) allows transmitting or receiving live video coverage of a person. Video games and adult content are the most popular among live streaming", "m": ["074r"], "s": ["tm","br","hd"]},
	{"c": 7, "w": 536, "p": "labeling", "t":"Labeling", "d": "Marketers use labeling to their products to bring identification and includes all written or graphic information. This kind of labeling helps a viewer to differentiate the product", "m": ["035s"], "s": ["tb","pt","hl"]},
	{"c": 3, "w": 384, "p": "normal", "t":"Normal", "d": "is a ray or vector that is perpendicular to a triangle, it can be calculated as the vector cross product of two (non-parallel) edges of the polygon", "m": ["016k"], "s": ["ts","fe","ps","hr"]},
	{"c": 7, "w": 1344, "p": "rocketscience", "t":"Rocket Science", "d": "", "m": ["074r"], "s": ["tm","fe","ph","hd"]},
	{"c": 3, "w": 384, "p": "mux", "t":"Mux", "d": "Multiplexing or muxing is the process of merging streams of video with audio", "m": ["016k"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 11, "w": 384, "p": "json", "t":"JSON", "d": "(JavaScript Object Notation) is a lightweight data-interchange format created by by Douglas Crockford in 2000", "m": ["054k"], "s": ["ts","fm","ph","hd"]},
	{"c": 8, "w": 943, "p": "unknownplayer", "t":"Unknown Player", "d": "", "m": ["016k"], "s": ["bb","hr"]},
	{"c": 8, "w": 356, "p": "megaman", "t":"Mega Man", "d": "(Rockman in Japan) is a action-platform video game developed by Capcom in 1987. Character was created by Akira Kitamura", "m": ["065s"], "s": ["ts","fe","ps","hr"]},
	{"c": 5, "w": 768, "p": "CAPTCHA", "t":"CAPTCHA", "d": "a contrived acronym for \"Completely Automated Public Turing test to tell Computers and Humans Apart\". The most common type of CAPTCHA was first invented in 1997 ", "m": ["035s"], "s": ["bb","hl"]},
	{"c": 7, "w": 407, "p": "breakintoit", "t":"Break into IT", "d": "", "m": ["035s"], "s": ["tb","fm","pt"]},
	{"c": 12, "w": 576, "p": "autoencoder", "t":"Autoencoder", "d": "is a type of artificial neural network used to learn efficient data codings in an unsupervised manner", "m": ["065s"], "s": ["fe","br","hr"], "b": 1},
	{"c": 12, "w": 576, "p": "gradientdescent", "t":"Gradient descent", "d": "is a first-order iterative optimization algorithm for finding a local minimum of a differentiable function. Gradient descent is generally attributed to Cauchy, who first suggested it in 1847", "m": ["070k"], "s": ["ts","fe","ps","hr"]},
	{"c": 7, "w": 675, "p": "learningmatrix", "t":"Learning Matrix", "d": "2×2 Matrix to Help Prioritize the Skills to Learn ", "m": ["070k"], "s": ["br"]},
	{"c": 8, "w": 384, "p": "twodots", "t":"TwoDots", "d": "is a puzzle mobile game developed by American indie studio Playdots in 2014", "m": ["073k"], "s": ["br","hr"]},
	{"c": 5, "w": 324, "p": "sticker", "t":"Sticker", "d": "Stickers is funny pictures with transparency (PNG) popular in messengers. Telegram has one of the best sticker functionality", "m": ["016k"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 2, "w": 720, "p": "428411", "t":"428 & 411", "d": "4xx client errors status codes: 428 (Precondition Required) The origin server requires the request to be conditional. 411 (Length Required) The request did not specify the length", "m": ["035s","071a"], "s": ["tb","fe","ps","hl"], "b": 1},
	{"c": 12, "w": 576, "p": "if", "t":"Is AI just a bunch of if else statements?", "d": "is an arcade game released in 1980 by Midway. Up to two players fight together in a series of monster-infested mazes", "m": ["063k"], "s": ["bb","hd"], "b": 1},
	{"c": 8, "w": 384, "p": "wizardofwor", "t":"Wizard of Wor", "d": "is an arcade game released in 1980 by Midway. Up to two players fight together in a series of monster-infested mazes", "m": ["016k"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 11, "w": 483, "p": "arrayzip", "t":"Array.zip()", "d": "Creates a sequence of pairs built out of two underlying sequences.", "m": ["067m"], "s": ["tm","fe","ps","hd"], "b": 1},
	{"c": 1, "w": 387, "p": "codecomment", "t":"Code comment", "d": "is a programmer-readable explanation or annotation in the source code of a computer program.", "m": ["064s"], "s": ["tb","fm","pt","hd"]},
	{"c": 7, "w": 347, "p": "MS-DOS", "t":"MS-DOS", "d": "is an operating system released by Microsoft in 1981. Renamed 86-DOS – owned by Seattle Computer Products, written by Tim Paterson", "m": ["073k"], "s": ["tr","ps","br","hd"], "b": 1},
	{"c": 10, "w": 650, "p": "cron", "t":"cron", "d": "is a classic UNIX daemon used to periodically execute tasks at a specific time. Developed by Ken Thompson in 1975. Named after Greek word for time, χρόνος (chronos).", "m": ["035s"], "s": ["tb","fm","pt"]},
	{"c": 5, "w": 324, "p": "functionkey", "t":"Function Key", "d": "is a key on a computer keyboard which can be programmed, appeared on Singer/Friden 2201 Flexowriter Programatic in 1965", "m": ["035s"], "s": ["tb","fe","pt","hl"]},
	{"c": 7, "w": 768, "p": "okboomer", "t":"OK boomer", "d": "is a meme which was popularized as a reaction to a video on TikTok of an unidentified older man", "m": ["067m"], "s": ["fm","ps","br"], "b": 1},
	{"c": 12, "w": 576, "p": "pytorch", "t":"PyTorch", "d": "is an open source machine learning library, used for applications such as computer vision and natural language processing, primarily developed by Facebook and released in 2016", "m": ["063k"], "s": ["tm","fe","ps","hd"]},
	{"c": 2, "w": 768, "p": "antipattern", "t":"Antipattern", "d": "is a pattern that tells how to go from a problem to a bad solution", "m": ["070k"], "s": ["ps","br"], "b": 1},
	{"c": 5, "w": 815, "p": "videotelephony", "t":"Videotelephony", "d": "", "m": ["073k"], "s": ["fe","ps","hd"]},
	{"c": 1, "w": 864, "p": "casestyle", "t":"Case Style", "d": "is a way to combine words into variable or function names in programming", "m": ["035s","071a"], "s": ["tb","ps"]},
	{"c": 11, "w": 419, "p": "iteratee", "t":"Iteratee", "d": "is a composable abstraction for incrementally processing sequentially presented chunks of input data", "m": ["065s"], "s": ["ps","br"]},
	{"c": 2, "w": 365, "p": "highcoupling", "t":"High Coupling", "d": "is considered a serious disadvantage in codebase, as it makes it difficult to understand the logic of modules, their modification, testing, and also reuse separately", "m": ["070k"], "s": ["tb","ps","hd"]},
	{"c": 12, "w": 576, "p": "lstm", "t":"LSTM", "d": "Long Short-Term Memory is one of the most widely used recurrent structures in sequence modeling, which use for Language Translation and Text Generation", "m": ["065s"], "s": ["ps"]},
	{"c": 12, "w": 576, "p": "cnn", "t":"CNN", "d": "Convolutional neural network is a class of deep neural networks, most commonly applied to analyzing visual imagery. Were invented in the 1980s", "m": ["053s"], "s": ["ps","fe","hl"]},
	{"c": 12, "w": 576, "p": "pandas", "t":"pandas", "d": "is a software library written on Python for data manipulation and analysis, developed by Wes McKinney in 2008", "m": ["065s"], "s": ["ts","fm","ps","hr"], "b": 1},
	{"c": 12, "w": 576, "p": "backpropagation", "t":"Backpropagation", "d": "short for \"backward propagation of errors\" is a widely used  algorithm for supervised learning of artificial neural networks using gradient descent", "m": ["053s"], "s": ["bb","hl"]},
	{"c": 7, "w": 506, "p": "developerlevel", "t":"Developer Level", "d": "is qualification level of skills and experience in software engineering", "m": ["035s"], "s": ["tb","ps"]},
	{"c": 0, "w": 324, "p": "text-shadow2", "t":"text-shadow", "d": "CSS 2 property. Defines the horizontal depth, vertical depth, blur, and color for a drop-shadow for text content in the element", "m": ["065s"], "s": ["ts","fe","hr"]},
	{"c": 7, "w": 768, "p": "islave", "t":"iSlave", "d": "", "m": ["035s"], "s": ["tb","ps","bb"]},
	{"c": 12, "w": 576, "p": "linearregression", "t":"Linear Regression", "d": "is a widely used technique in data science which commonly used type of predictive analysis", "m": ["016k"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 12, "w": 576, "p": "k-means", "t":"K-means", "d": "is one of the simplest unsupervised learning algorithms that solves the well known clustering problem", "m": ["066i"], "s": ["tb","fe","pt","hd"]},
	{"c": 12, "w": 576, "p": "keras", "t":"TensorFlow ❤ Keras", "d": "Keras is an open-source neural-network library written in Python.  It was developed by Francois Chollet in 2015", "m": ["065s"], "s": ["ts","fe","ps","hr"]},
	{"c": 12, "w": 576, "p": "gan", "t":"GAN", "d": "A Generative Adversarial Network architecture comprising two competing neural networks within the framework of a zero-sum game. Was by Ian Goodfellow and his colleagues in 2014", "m": ["064s"], "s": ["tb","fe","ps","hd"]},
	{"c": 11, "w": 576, "p": "pairedheap", "t":"Paired Heap", "d": "are a type of self-adjusting binomial heap, which Self-adjusting structures rearrange themselves when operations happen to remain balanced", "m": ["035s"], "s": ["ps","bb"]},
	{"c": 1, "w": 384, "p": "generictype", "t":"Generic Type", "d": "allow you to define a class with placeholders for the type. The generic type is usually specified in angle brackets", "m": ["065s"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 7, "w": 576, "p": "instamanifest", "t":"InstaManifest", "d": "Collaboration with <a href='https://t.me/soulfulnude'>SoulfulNude</a>", "m": ["069m"], "s": ["ph","bb","hd"]},
	{"c": 8, "w": 432, "p": "corewar", "t":"Core War", "d": " is a 1984 programming game created by D. G. Jones and A. K. Dewdney in which two or more battle programs written in an abstract assembly language called Redcode", "m": ["067m"], "s": ["tb","fm","ps","hd"], "b": 1},
	{"c": 7, "w": 459, "p": "programmer", "t":"Programmer", "d": "", "m": ["066i"], "s": ["br","hd"]},
	{"c": 12, "w": 407, "p": "pipe", "t":"Pipe", "d": "operators, available in magrittr and other R packages, process a data-object using a sequence of operations by passing the result of one step as input for the next step", "m": ["065s"], "s": ["ts","fe","ps","hr"]},
	{"c": 10, "w": 864, "p": "chmod", "t":"chmod", "d": "is the command which is used to change the access permissions of file or directory", "m": ["065s"], "s": ["ps","bb","hr"], "b": 1},
	{"c": 1, "w": 324, "p": "addition", "t":"Addition", "d": "is one of the four basic operations of arithmetic, that signified by the plus symbol +", "m": ["067m"], "s": ["tb","ps","fm","hd"], "b": 1},
	{"c": 2, "w": 432, "p": "antivirus", "t":"Antivirus", "d": "software is a computer program used to prevent, detect, and remove malware", "m": ["068a"], "s": ["tm","fm","bb","hd"], "b": 1},
	{"c": 0, "w": 768, "p": "flex-shrink", "t":"flex-shrink", "d": "is a CSS 3 property and sub-property of the Flexible Box Layout module, which determines how much the flex item will shrink", "m": ["065s"], "s": ["ts","ps","fe","br","hr"], "b": 1},
	{"c": 7, "w": 360, "p": "siliconvalleymafia", "t":"Silicon Valley Mafia", "d": "is the act of casting a reference of a base(parent) class to one of its sub(child) classes", "m": ["067m"], "s": ["tb","ps","fe","hd"]},
	{"c": 1, "w": 324, "p": "ducktyping", "t":"Duck Typing", "d": "means that an operation does not formally specify the requirements, but just tries it out with what is given", "m": ["063k"], "s": ["fm","bb"], "b": 1},
	{"c": 1, "w": 768, "p": "downcasting", "t":"Downcasting", "d": "is the act of casting a reference of a base(parent) class to one of its sub(child) classes", "m": ["035s"], "s": ["tb","ps","hl"]},
	{"c": 11, "w": 768, "p": "string", "t":"String", "d": "is a sequence(sometimes array) of characters that is treated as a single data structure(or type) and terminated by null character '\0'", "m": ["035s"], "s": ["tb","fe","ps","bb","hl"], "b": 1},
	{"c": 10, "w": 324, "p": "deployment", "t":"Deployment", "d": "is the process of remotely installing software on multiple server within a network from a central location", "m": ["066i"], "s": ["tb","fm","pt"], "b": 1},
	{"c": 1, "w": 432, "p": "functionallens", "t":"Functional Lens", "d": "combines a “getter” function and a “setter” function into a single unit, which are separated from target object.", "m": ["065s"], "s": ["ps","br"], "b": 1},
	{"c": 2, "w": 432, "p": "sphagetticode", "t":"Sphagetti Code", "d": "is a unstructured and difficult-to-maintain source code", "m": ["065s"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 2, "w": 506, "p": "hotfix", "t":"Hotfix", "d": "is a software update designed to fix a bug or security hole in a program", "m": ["062u"], "s": ["ps","bb"]},
	{"c": 7, "w": 385, "p": "covfefe", "t":"covfefe", "d": "Covfefe is a viral tweet of US President Donald Trump made on May 31, 2017, full message: \"Despite the constant negative press covfefe\"", "m": ["066i"], "s": ["tm","fm","pt"]},
	{"c": 11, "w": 385, "p": "unorderedcollection", "t":"Unordered Collection", "d": "is a Data Structure, a group of elements in no particular order", "m": ["063k"], "s": ["tm","fm","ps"], "b": 1},
	{"c": 1, "w": 406, "p": "legacycode", "t":"Legacy Code", "d":"is source code that relates to a no-longer supported", "m": ["064s"], "s": ["ph", "br", "hd"]},
	{"c": 10, "w": 405, "p": "rabbitmq", "t":"RabbitMQ", "d": "is an open-source multi-protocol message-broker allows you to organize a fail-safe cluster with full data replication to several nodes", "m": ["053s"], "s": ["fm","ps","hl"]},
	{"c": 7, "w": 768, "p": "fakenews", "t":"Fake News", "d": "is a type of journalism/propaganda/marketing that consists of deliberate disinformation or hoaxes spread via news media & online social media", "m": ["065s"], "s": ["ps"]},
	{"c": 0, "w": 324, "p": "mix-blend-mode", "t":"mix-blend-mode", "d": "is a CSS 3 property sets how an element's content should blend with the content of the element's parent and background", "m": ["065s"], "s": ["ts", "fe", "ps", "hr"], "b": 1},
	{"c": 11, "w": 864, "p": "key-value", "t":"Key-Value", "d": "is a two paired values, one of which you have designated to be a \"key\" and the other you have designated to be the \"value\". This conception widely used in data structures and databases", "m": ["063k"], "s": ["ps"]},
	{"c": 8, "w": 345, "p": "mmorpg", "t":"MMORPG", "d": "is online role-playing multiplayer game which allow thousands of gamers to play in the virtual world at the same time via Internet", "m": ["065s"], "s": ["ts", "fe", "ps", "hr"]},
	{"c": 11, "w": 833, "p": "fat32", "t":"FAT32", "d":"is a computer file system architecture, was originally designed in 1977(FAT8). The maximum possible size for a file on a FAT32 volume is 4 GB", "m": ["064s"], "s": ["bb"]},
	{"c": 10, "w": 864, "p": "port", "t":"Port", "d": "is a 16-bit unsigned integer(ranging from 0 to 65535). Ports are identified for each protocol(TCP, UDP, …) and always associated with an IP address", "m": ["065s"], "s": ["ts", "fe", "ps", "hr"]},
	{"c": 8, "w": 864, "p": "commanderkeen", "t":"Commander Keen", "d":"Commander Keen is a series of side-scrolling platform video games developed primarily by id Software and released for MS-DOS in 1990. Game engine based on programmer John Carmack's algorithm \"adaptive tile refresh\"", "m": ["064s"], "s": ["tb", "fm", "pt", "hd"]},
	{"c": 1, "w": 660, "p": "bitwiseshifts", "t":"Bitwise Shifts", "d":"&lt;&lt; This operator shifts the first operand the specified number of bits to the left. &gt;&gt; This operator shifts the first operand the specified number of bits to the right.", "m": ["016k"], "s": ["bb","hr"]},
	{"c": 5, "w": 389, "p": "dialogbox", "t":"Dialog Box", "d":"is a UI element in the form of a small window that communicates information to the user and prompts them for a response", "m": ["063k"], "s": ["fe","tm","hd"]},
	{"c": 5, "w": 410, "p": "stories", "t":"Stories", "d":"Story is social media type picture or video displays for a short time and viewable for up to 24 hours, invented by Snapchat in 2013", "m": ["062u"], "s": ["fe","tb","ps","hb"], "b": 1},
	{"c": 0, "w": 768, "p": "first-letter", "t":"::first-letter", "d":"CSS pseudo-element applies styles to the first letter of the first line of a block-level element", "m": ["016k"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 5, "w": 356, "p": "darktheme", "t":"Dark Theme", "d":"", "m": ["063k"], "s": ["ps","bb","hd"]},
	{"c": 11, "w": 595, "p": "integer", "t":"Integer", "d":"is a data type that represents some range of mathematical integers. Integers like a natural(whole) numbers, but also also include negative numbers", "m": ["062u"], "s": ["tb","ps"]},
	{"c": 5, "w": 384, "p": "safetylevels", "t":"Safety Levels", "d":"Moderate: Female breasts, bare/thong bottom, see through topless nudity, pasties, etc…<br>Restricted: Genitalia/pubic hair ", "m": ["053s"], "s": ["tb", "ps", "hl"]},
	{"c": 9, "w": 385, "p": "utf8", "t":"UTF-8", "d":"is a Unicode Transformation Format – 8-bit, Standard was originally designed by Ken Thompson and Rob Pike in 1992", "m": ["063k"], "s": ["tm","fm","ps","hd"]},
	{"c": 8, "w": 864, "p": "pause", "t":"Pause", "d":"", "m": ["053s"], "s": ["ps"]},
	{"c": 7, "w": 576, "p": "eth", "t":"Ethereum", "d":"is a cryptocurrency and blockchain-based distributed computing platform and operating system featuring smart contract functionality released in July 2015 by Vitalik Buterin", "m": ["034m"], "s": ["tm","fm","pt","hd"]},
	{"c": 7, "w": 576, "p": "eos", "t":"EOS", "d":"is a cryptocurrency and a blockchain platform for the development of decentralized applications (DApps), similar to Ethereum started with ICO in June 2017 by software programmer and cryptocurrency entrepreneur Daniel Larimer", "m": ["060c"], "s": ["ts","fe","ps","hd"]},
	{"c": 7, "w": 576, "p": "xmr", "t":"Monero", "d":"is a cryptocurrency focused on privacy created in April 2014 by Nicolas van Saberhagen based on the CryptoNight proof-of-work hash algorithm, which comes from the CryptoNote protocol allows blockchain obfuscation.", "m": ["053s"], "s": ["bb","hl"]},
	{"c": 7, "w": 576, "p": "etn", "t":"Electroneum", "d":"is a British cryptocurrency launching via an Initial Coin Offering (ICO) on September 2017 by Richard Ells. Developed to be used in the mobile gaming and online gambling markets", "m": ["001b"], "s": ["tb","fm","pt"]},
	{"c": 7, "w": 576, "p": "rvn", "t":"Ravencoin", "d":"is a cryptocurrency focused on privacy was launched in October 2017 with new X16 mining algorithm, white paper is signed by Boston-area blockchain adviser Bruce Fenton and Salt Lake City-based Tron Black", "m": ["034m"], "s": ["tm","fe","pt","hr"]},
	{"c": 7, "w": 576, "p": "btc", "t":"Bitcoin", "d":"is a first cryptocurrency invented by an unknown person or group of people using the name Satoshi Nakamoto in August-October 2008, and started in January 2009. Nick Szabo, creator of bit gold in 1998 suspected to be Nakamoto", "m": ["061t"], "s": ["bb", "hd"]},
	{"c": 7, "w": 576, "p": "ltc", "t":"Litecoin", "d":"is a cryptocurrency (fork of the Bitcoin Core client) released in October 2011 by Charlie Lee a Google employee and former Engineering Director at Coinbase", "m": ["016k"], "s": ["ts","fe","pt","hr"]},
	{"c": 7, "w": 576, "p": "zcash", "t":"ZCash", "d":"is a anonymous cryptocurrency aimed at using cryptography to provide enhanced privacy announced in January 2016 by Zooko Wilcox and released in October same year", "m": ["061t"], "s": ["tm","pt","hd"]},
	{"c": 7, "w": 576, "p": "tron", "t":"TRON", "d":"is both a currency(ERC-20 token TRX) and distributed blockchain content storage and sharing technology but aimed at the mammoth global content and entertainment sector, introduced in September 2017 by Justin Sun", "m": ["054k"], "s": ["ts","fm","pt","hd"]},
	{"c": 7, "w": 576, "p": "dash", "t":"Dash", "d":"is a cryptocurrency with anonymous transactions and is a form of decentralized autonomous organization (DAO) launched in January 2014 as Xcoin by Evan Duffield", "m": ["062u"], "s": ["tb","fe","ps","hb"]},
	{"c": 7, "w": 576, "p": "xrp", "t":"Ripple", "d":"is both a currency(ERC-20 token) and a platform targets currency exchange and remittance built by Arthur Britto and David Schwartz in 2012", "m": ["061t"], "s": ["tm","fm","pt","hd"]},
	{"c": 7, "w": 576, "p": "doge", "t":"Dogecoin", "d":"is a cryptocurrency featuring a likeness of the Shiba Inu dog from the Doge Internet meme as its logo. Introduced as a joke currency on December 2013 by Billy Markus", "m": ["053s"], "s": ["br","hl"]},
	{"c": 1, "w": 864, "p": "urlencoding", "t":"URL Encoding", "d":"replaces unsafe ASCII characters with a % followed by two hexadecimal digits, because URLs cannot contain spaces, spaces also can be replaced with + sign", "m": ["063k"], "s": ["tm","hd"]},
	{"c": 2, "w": 432, "p": "imagenotfound", "t":"Image Not Found", "d":"", "m": ["062u"], "s": ["tb","ps"], "b": 1},
	{"c": 1, "w": 395, "p": "rust", "t":"Rust", "d":"is a programming language focused on safe concurrency, grew out of a pet project started in 2006 by Mozilla employee Graydon Hoare, released in 2010", "m": ["061t"], "s": ["tm","pt","hd"]},
	{"c": 3, "w": 415, "p": "mp4", "t":"MPEG-4 Part 14", "d":"or MP4 is a digital multimedia container format most commonly used to store video. ....fftp designation specifies which codec is used", "m": ["053s"], "s": ["tb","fm","ps","hl"]},
	{"c": 10, "w": 768, "p": "fold", "t":"fold", "d":"is a Unix command used for making a file with wide text lines more readable by limiting lines width on setted value", "m": ["016k"], "s": ["br"]},
	{"c": 6, "w": 451, "p": "recursive", "t":"RECURSIVE", "d":"Recurcive CTEs (Common Table Expressions) are a powerful construct within PostgreSQL, it defined in the WITH clause. CTEs allows to work with temporary dataset and transform it", "m": ["053s"], "s": ["tb","fe","ps","hl"]},
	{"c": 2, "w": 768, "p": "dataprivacy", "t":"Data Privacy", "d":"Eight years ago I made <a href='https://exeypanteleev.com/ui/searchbox'>Search Box geekography</a> It's new variant with same charming model, reflecting the current situation with search engines and other companies(such FB) which earning their main money on internet ads ", "m": ["034m"], "s": ["pt"]},
	{"c": 11, "w": 384, "p": "mutablebag", "t":"Mutable Bag", "d":"Bag(also called multisets) is a Data Structure whose elements are unordered and may contain duplicate entries", "m": ["034m"], "s": ["bb","hd"]},
	{"c": 10, "w": 347, "p": "daemonize", "t":"daemonize", "d":"daemon is a computer a that runs as a background process. Girld is not errata, names of the daemon processes end with the letter d", "m": ["016k"], "s": ["ts","fm","pt","hr"]},
	{"c": 11, "w": 864, "p": "lzma", "t":"LZMA", "d":"The Lempel–Ziv–Markov chain algorithm (LZMA) is an algorithm used to perform lossless data compression. LZMA SDK and 7z(7-Zip archiver) is released by Igor Pavlov in 1999 7-zip makes archives smaller by 30-70% than zip", "m": ["001b"], "s": ["bb"], "b": 1},
	{"c": 9, "w": 384, "p": "statueofliberty", "t":"🗽", "d":"Statue of Liberty or U+1F5FD was approved as part of Unicode 6.0 in 2010 and added to Emoji 1.0 in 2015", "m": ["054k"], "s": ["ts","fm","pt"]},
	{"c": 11, "w": 864, "p": "boolean", "t":"Boolean", "d":"is a primitive data structure that has one of two possible values (usually denoted true and false), intended to represent the two truth values of logic", "m": ["034m"], "s": ["bb"]},
	{"c": 2, "w": 384, "p": "referencecycle", "t":"Reference cycle", "d":"is a situation in running program code when exists one or more objects referencing each other. It's leads to memory leakes, and app takes more RAM", "m": ["053s", "056m"], "s": ["ts","tb","fe","ps","hr","hl"]},
	{"c": 3, "w": 384, "p": "adam7", "t":"Adam7", "d":"is an interlacing algorithm for raster images, optionally used in PNG images. Adam7 is named after Adam M. Costello, who suggested it on Feb. 2, 1995", "m": ["060c"], "s": ["br"]},
	{"c": 9, "w": 384, "p": "dice", "t":"🎲", "d":"Dice or U+1F3B2 was approved as part of Unicode 6.0 in 2010 and added to Emoji 1.0 in 2015", "m": ["058k"], "s": ["tm","fe","ps","hd"]},
	{"c": 2, "w": 768, "p": "btard", "t":"/b/tard", "d":"One who joins other internet superheroes in the poasting of content on /b/. A true /b/tard knows all the memes of the land and is disgusted by nothing. A true hardened warrior. 7chan, 4chan, iichan, 12chan, that crazy russian /b/. It doesn't matter. We are one. We are Anonymous.", "m": ["035s"], "s": ["tb","fm","ph","hl"]},
	{"c": 10, "w": 384, "p": "rmrf", "t":"rm -rf", "d":"Unix-based command rm -rf is the same as rm -r -f 'rm -r' remove directories recursively<br> '-f' ignore prompt (force)", "m": ["059m"], "s": ["tm","fe","ps","hb"]},
	{"c": 9, "w": 864, "p": "awkward", "t":"😬", "d":"Awkward or U+1F62C was approved as part of Unicode 6.1 in 2012 and added to Emoji 1.0 in 2015", "m": ["053s"], "s": ["tb","ps","hb"]},
	{"c": 8, "w": 324, "p": "tetris", "t":"Tetris", "d":"is a tile-matching puzzle game, designed and programmed by Russian game designer Alexey Pajitnov and released on June 6, 1984", "m": ["035s"], "s": ["tm","fe","pt","hl"]},
	{"c": 11, "w": 384, "p": "suffixarray", "t":"Suffix Array", "d":"Suffix array is a sorted array of all suffixes of a string, it was introduced by Manber&Myers in 1990 as a space efficient alternative to suffix trees", "m": ["053s"], "s": ["tb","fe","ps","hl"]},
	{"c": 9, "w": 324, "p": "prohibited", "t":"18🈲", "d":"“prohibited” CJK unified ideograph was approved as part of Unicode 6.0 in 2010 and added to Emoji 1.0 in 2015", "m": ["060c"], "s": ["ts","ps","hd"]},
	{"c": 4, "w": 591, "p": "canvas2", "t":"canvas", "d":"is HTML5 tag which used to draw graphics", "m": ["054k"], "s": ["br"], "b": 1},
	{"c": 2, "w": 384, "p": "compilationerror", "t":"Compilation error", "d":"it's a state when a compiler fails to assemble a piece source code of application", "m": ["055f"], "s": ["ts","fe","ps","hl"]},
	{"c": 9, "w": 384, "p": "clover", "t":"🍀", "d":"Clover or U+1F340 was approved as part of Unicode 6.0 in 2010 and added to Emoji 1.0 in 2015", "m": ["053s"], "s": ["bb","hl"]},
	{"c": 0, "w": 1024, "p": "text-overflow-ellipsis", "t":"text-overflow: ellipsis", "d":"The text-overflow property specifies how overflowed content that is not displayed should be signaled to the user. It can be clipped, display an ellipsis \"…\"", "m": ["035s"], "s": ["tb","fe","pt","hl"]},
	{"c": 9, "w": 864, "p": "meditation", "t":"🧘", "d":"Meditation or U+1F9D8 was approved as part of Unicode 10.0 in 2017 and added to Emoji 5.0 in 2017", "m": ["053s"], "s": ["ps"]},
	{"c": 11, "w": 384, "p": "b-heap", "t":"B-Heap", "d":"Binomial Heap is a set of Binomial Trees where each Binomial Tree follows Min Heap property. The main application of B-Heap is as implement priority queue", "m": ["053s"], "s": ["br"]},
	{"c": 7, "w": 384, "p": "binaryprefixes", "t":"Binary prefixes", "d":"In 1998 IEC published standards for binary prefixes, requiring that the gigabyte(GB) strictly denote 1000^3 bytes and gibibyte(GiB) denote 1024^3 bytes", "m": ["053s", "056m"], "s": ["tb","ts","fe","ps","hl","hr"]},
	{"c": 2, "w": 384, "p": "trojan", "t":"Trojan", "d":"is malicious computer program, it’s takes name from the story of the Trojan horse, it misleads users of its true intent, its creating backdoors, spying", "m": ["035s"], "s": ["tb","fm","pt"]},
	{"c": 9, "w": 864, "p": "slightlysmilingface", "t":"🙂", "d":"Slightly Smiling Face was approved as part of Unicode 7.0 in 2014 and added to Emoji 1.0 in 2015", "m": ["059m"], "s": ["tm","fe","ps","hb"]},
	{"c": 11, "w": 864, "p": "stack", "t":"Stack", "d":"is a linear data structure which follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out)", "m": ["053s"], "s": ["ps"], "b": 1},
	{"c": 9, "w": 384, "p": "fire", "t":"🔥", "d":"Fire or U+1F525 is a emoji character that was added to Emoji 1.0 in 2015", "m": ["058k"], "s": ["ts","ps"]},
	{"c": 9, "w": 768, "p": "bread", "t":"🍞", "d":"Bread or U+1F35E is a emoji character that was added to Emoji 1.0 in 2015", "m": ["054k"], "s": ["fe","pt","hd"], "b": 1},
	{"c": 4, "w": 864, "p": "track", "t":"&lt;track&gt;", "d":"is a HTML5 tag is used to specify timed text tracks for media(video/audio) elements", "m": ["060c"], "s": ["ts","ps"]},
	{"c": 9, "w": 324, "p": "hearteyescat", "t":"😻", "d":"Heart Eyes Cat or U+1F63B is a emoji character that was added to Emoji 1.0 in 2015", "m": ["053s"], "s": ["tb","fm","ps","hl"], "b": 1},
	{"c": 2, "w": 864, "p": "typeerror", "t":"Type Error", "d": "define an error when a value is not of the expected type", "m": ["034m"], "s": ["tm","pt"]},
	{"c": 3, "w": 567, "p": "tiling", "t":"Tiling", "d":"is the process of filling surface with repeated image pattern that used in computer graphics to generate bigger images or backgroundss", "m": ["053s"], "s": ["bb"], "b": 1},
	{"c": 2, "w": 462, "p": "flooding", "t":"Flooding", "d":"means to disturb the chat by sending a lot of offtopic messages", "m": ["053s"], "s": ["tb","fe","ps","hl"]},
	{"c": 9, "w": 461, "p": "beachwithumbrella", "t":"🏝️", "d":"Beach With Umbrella or U+1F3D6 is a emoji character that was added to Emoji 1.0 in 2015", "m": ["058k"], "s": ["br"]},
	{"c": 8, "w": 576, "p": "digdug", "t":"Dig Dug", "d":" is an arcade game developed by Namco in Japan in 1982", "m": ["045k"], "s": ["tm","fe","pt","hb"]},
	{"c": 10, "w": 720, "p": "fullstack", "t":"Full Stack", "d":"Full Stack development refers to the development of both front-end(UI/UX) and back-end(Server, DB) parts of an application", "m": ["053s", "056m"], "s": ["ts","ps","hr"]},
	{"c": 2, "w": 384, "p": "avatarisrequired", "t":"Avatar is Required", "d":"", "m": ["054k"], "s": ["ts","fm","ph"]},
	{"c": 9, "w": 622, "p": "pawprints", "t":"🐾", "d":"Paw Prints or U+1F37A is a emoji character that was added to Emoji 1.0 in 2015", "m": ["016k"], "s": ["bb"]},
	{"c": 8, "w": 576, "p": "dounodewei", "t":"Do U No De Wei?", "d":"On 20th February 2017, YouTuber Gregzilla made a review of the 2013 game 'Sonic Lost World', which featured a parody animation of the character Knuckles. On December 2017 swarm of VRChat players wearing Ugandan Knuckles starts avatars troll other players", "m": ["053s"], "s": ["tb","fe","ps","hl"]},
	{"c": 11, "w": 768, "p": "nullgraph", "t":"Null Graph", "d":"is a graph data structure which has no edges hence this graph consists only isolated nodes", "m": ["059m"], "s": ["fe","br","hb"], "b": 1},
	{"c": 10, "w": 576, "p": "fedora", "t":"Fedora", "d":"is a linux distribution used to test new features on users before Redhat Release, focused primarily on the desktop, released in 2003 by Red Hat", "m": ["053s", "056m"], "s": ["ts","fe","ps","hr"]},
	{"c": 10, "w": 576, "p": "debian", "t":"Debian", "d":"is one of the oldest linux distribution, the standard for the backend/server, but also suitable for the desktop purposes, released in 1993 by Ian Murdock", "m": ["057b"], "s": ["br","hr"]},
	{"c": 10, "w": 576, "p": "alpine", "t":"Alpine Linux", "d":"is a distro which lightweight, undemanding to resources and safe, created in 2011 in Norway", "m": ["055f"], "s": ["tm","fe","ps","hl"]},
	{"c": 10, "w": 576, "p": "raspbian", "t":"Raspbian", "d":"is a linux distribution, made for single-board computers Raspberry Pi and released in 2015", "m": ["040s"], "s": ["br","hb"]},
	{"c": 10, "w": 576, "p": "astralinux", "t":"Astra Linux", "d":"is a russian distro, certified by russian siloviki to work with “top secret” content, and also suitable for ordinary users, released in 2010 by “NPO RusBITEch”", "m": ["059m"], "s": ["tm","fe","ps","hb"]},
	{"c": 10, "w": 576, "p": "linuxmint", "t":"Linux Mint", "d":"is one of the best desktop distributions, based on Ubuntu, was created in 2006 by Clément Lefèbvre", "m": ["054k"], "s": ["tm","fe","ph","hd"]},
	{"c": 10, "w": 576, "p": "ubuntu", "t":"Ubuntu", "d":"is linux distro that the standard for the desktop, uses by 20 millions of users, branched off from Debian distro in 2004 year", "m": ["053s", "056m", "022o"], "s": ["br","hr","hl"]},
	{"c": 10, "w": 576, "p": "opensuse", "t":"openSUSE", "d":"is linux for universal purposes, released in 1992 by Peter McDonald, is based on the no longer supported Slackware", "m": ["058k"], "s": ["ts","fe","br","hd"]},
	{"c": 10, "w": 576, "p": "tinycore", "t":"Tiny Core Linux", "d":"is a super-lightweight and modular linux distribution, use about 16 MB of disk space and 46 MB of RAM, developed since 2009 by Robert Shingledecker", "m": ["016k"], "s": ["ps","fe","ps","hr"]},
	{"c": 10, "w": 576, "p": "archlinux", "t":"Arch Linux", "d":"is a very customizable and lightweight distribution that can be installed from the network through the command line, was created in 2002 by Judd Vinet", "m": ["053s"], "s": ["tb","fe","br","hl"]},
	{"c": 10, "w": 576, "p": "elementaryos", "t":"elementary OS", "d":"is a Linux distribution based on Ubuntu and released in 2011 by Daniel Foré", "m": ["035s"], "s": ["tb","fe","pt","hl"], "b": 1},
	{"c": 10, "w": 576, "p": "gentoo", "t":"Gentoo", "d":"is a Linux distribution built with Portage package management system and released at 1997 year by Daniel Robbins", "m": ["059m"], "s": ["tm","fe","br","hb"]},
	{"c": 1, "w": 432, "p": "threadsleep", "t":"thread.sleep", "d":"suspends the current thread of tasks for the specified amount of time", "m": ["016k"], "s": ["ts","fm","ps","hb"]},
	{"c": 9, "w": 720, "p": "beermug", "t":"🍺", "d":"Beer Mug or U+1F37A is a emoji character that was added to Emoji 1.0 in 2015", "m": ["053s", "056m"], "s": ["tb","ts","fm","ps","pt"]},
	{"c": 1, "w": 864, "p": "asymmetricalcryptography", "t":"Asymmetrical cryptography", "d":"is cryptographic system that uses pairs of keys: public key which may be spread widely, and private key which are known only to the owner", "m": ["053s", "022o"], "s": ["bb"]},
	{"c": 9, "w": 384, "p": "pigface", "t":"🐷", "d":"Pig Face or U+1F437 is a emoji characters that was approved as part of Unicode 6.0 in 2010", "m": ["035s"], "s": ["tb","fm","pt"]},
	{"c": 9, "w": 384, "p": "egg", "t":"🍳", "d":"Egg(Cooking) or  U+1F373 is a emoji characters that was approved as part of Unicode 6.0 in 2010", "m": ["054k"], "s": ["tm","fe","ph","hd"]},
	{"c": 9, "w": 432, "p": "hearteyes", "t":"😍", "d": "Heart Eyes or U+1F60D is a emoji character that was approved as part of Unicode 6.0 in 2010", "m": ["053s"], "s": ["tb","fe","hl"]},
	{"c": 5, "w": 864, "p": "usb", "t":"USB", "d": "is Universal Serial Bus, is an industry standard that defines cables, and connectors. USB Type-A connector (12 x 4.5mm) introduced in 1996, smaller version Type-C connector (8.4 x 2.6mm) was finalized in 2014", "m": ["035s"], "s": ["bb"]},
	{"c": 5, "w": 384, "p": "orientationlockoff", "t":"Orientation Lock: Off", "d": "Orientation Lock is smartphone screen mode that can be on and off, when it's off it's allows flipping from portrait to landscape view", "m": ["055f"], "s": ["tm","fe","ps","hl"]},
	{"c": 9, "w": 384, "p": "confounded", "t":"😖", "d": "Confounded Face or U+1F616 is a emoji character that was approved as part of Unicode 6.0 in 2010", "m": ["035s"], "s": ["tb","pt"]},
	{"c": 5, "w": 384, "p": "follow", "t":"Follow Button", "d":"is UI element that allows to subscribe to social network profile and receive updates from it", "m": ["053s"], "s": ["bb","hl"], "b": 1},
	{"c": 2, "w": 864, "p": "butthurt", "t":"Butthurt", "d":"is inappropriately negative emotional response from a perceived personal insult with a strong feelings of shame", "m": ["054k"], "s": ["tm","fe","br","hd"]},
	{"c": 0, "w": 461, "p": "height101", "t":"Vertical scrollbar always visible", "d":"height: 101%; in CSS make main scrollbar visible and active in all browsers", "m": ["053s"], "s": ["br","hl"]},
	{"c": 8, "w": 384, "p": "minesweeper", "t":"Minesweeper", "d": "is a single-player puzzle game, early ancestor of that was Jerimac Ratliff's Cube made in 1960s", "m": ["016k"], "s": ["ts","fe","ps","hr"], "b": 1},
	{"c": 0, "w": 576, "p": "border-collapse", "t":"border-collapse: collapse", "d":"border-collapse is CSS2 property, it's can be used for HTML tables with value 'collapse' to collapse doubled borders into single line borders", "m": ["053s"], "s": ["tb","ps"]},
	{"c": 9, "w": 864, "p": "eyes", "t":"👀", "d":"Eyes or U+1F440 is a emoji character that was approved as part of Unicode 6.0 in 2010. Do you remeber meme 'Ivanka looking at Trudeau'?", "m": ["055f"], "s": ["bb"]},
	{"c": 8, "w": 432, "p": "loadingscreen", "t":"Loading Screen", "d":"In 2014 Lindsay Lohan sued GTA publisher for what she believed was an unauthorized depiction of her image in Grand Theft Auto V at game loading screens", "m": ["051d"], "s": ["tm","fe","ph","hd"]},
	{"c": 4, "w": 970, "p": "s", "t":"s", "d":"is HTML5 tag is used for display strike out text which indicate content that is incorrect", "m": ["053s"], "s": ["ps"]},
	{"c": 9, "w": 864, "p": "kissing&laughing", "t":"😘😂", "d":"Kissing(U+1F618) and Laughing((U+1F602) are a emoji characters that was approved as part of Unicode 6.0 in 2010", "m": ["054k"], "s": ["br"]},
	{"c": 9, "w": 576, "p": "crazyface", "t":"😜", "d":"Crazy Face or U+1F61C is a emoji character that was approved as part of Unicode 6.0 in 2010", "m": ["053s"], "s": ["tb","ps","hl"], "b": 1},
	{"c": 5, "w": 576, "p": "webcam", "t":"Webcam", "d":"(web camera) is a digital camera that's connected to a computer and can stream its image to internet or other network. First webcam was QuickCam released in 1994 by Connectix for Apple Macintosh", "m": ["035s"], "s": ["br","hb"]},
	{"c": 0, "w": 384, "p": "selection", "t":"::selection", "d": "is CSS3 pseudo class defines style of selected text", "m": ["053s"], "s": ["tb","fe","ps","hl"]},
	{"c": 3, "w": 864, "p": "invert", "t":"Color inversion", "d": "is a computer graphics processing feature where colors replaced to opposite values, black becomes white, yellow becomes blue and so on", "m": ["051d"], "s": ["br"]},
	{"c": 3, "w": 350, "p": "rgb", "t":"RGB", "d": "is a color model in which mixed Red-Green-Blue lights can make any color. It created by Thomas Young & Hermann Helmholtz in 19th century", "m": ["035s"], "s": ["tm","fe","pt","hl"]},
	{"c": 8, "w": 500, "p": "1up", "t":"1-UP", "d": "1-Up Mushrooms are Super Mario game item that give the player an extra life. First appeared in Super Mario Bros in 1985", "m": ["034m"], "s": ["bb","hd"], "b": 1},
	{"c": 9, "w": 324, "p": "sliceofpizza", "t":"🍕", "d": "Slice of Pizza or U+1F355 is a emoji character that was approved as part of Unicode 6.0 in 2010", "m": ["053s"], "s": ["tb","ps","hl"]},
	{"c": 8, "w": 1024,"p": "gameover", "t":"Game Over", "d": "is a message in video games which signals that the game has ended. Phrase initially used in early 1950s in electromechanical pinball game machines, that show it with a lightbulb.", "m": ["045k"], "s": ["br","hl"]},
	{"c": 6, "w": 432, "p": "innerjoin", "t":"INNER JOIN", "d": "creates a new result table by combining column values of two or more tables, there must be at least some matching data between tables that are being compared by condition.", "m": ["051d"], "s": ["tm","fe","ph","hd"], "b": 1},
	{"c": 7, "w": 539, "p": "telegram", "t":"Telegram", "d": "is a cloud-based instant messaging service launched in 2013 by brothers Nikolai and Pavel Durov. I post backstage in <a href='https://exeypanteleev.com/telegram'>the telegram channel</a>", "m": ["035s"], "s": ["tb","ps"]},
	{"c": 2, "w": 768, "p": "nointernet", "t":"No Internet Connection", "d": "T-Rex mini game only accessable in Google Chrome browser when you're disconnected from internet", "m": ["045k"], "s": ["tb","fe","pt","hb"], "b": 1},
	{"c": 9, "w": 576, "p": "pileofpoo", "t":"💩", "d": "Pile of Poo or U+1F4A9 is a emoji character that was approved as part of Unicode 6.0 in 2010", "m": ["053s"], "s": ["bb","hl"], "b": 1},
	{"c": 3, "w": 576, "p": "metal", "t":"Metal", "d": "is a low-overhead computer graphics API developed by Apple and released in 2014", "m": ["034m"], "s": ["tm","fe","pt","hd"]},
	{"c": 8, "w": 576, "p": "spritekit", "t":"SpriteKit", "d": "is a framework for making 2D games developed by Apple and released in 2013", "m": ["036h"], "s": ["tb","fe","ps"]},
	{"c": 3, "w": 576, "p": "cardboard", "t":"Cardboard", "d": "is a virtual reality (VR) platform developed by Google and released in 2014", "m": ["053s"], "s": ["tb","fm","ps","hl"]},
	{"c": 3, "w": 576, "p": "threejs", "t":"three.js", "d": "is a cross-browser JavaScript library used to display 3D computer graphics created by Ricardo Cabello aka Mr.doob and released in 2010", "m": ["001b"], "s": ["tb","fm","pt","hr"]},
	{"c": 8, "w": 576, "p": "unity", "t":"Unity", "d": "is a cross-platform game engine, first announced at Apple's WWDC in 2005", "m": ["037s","050e"], "s": ["br"], "b": 1},
	{"c": 8, "w": 576, "p": "libgdx", "t":"libGDX", "d": "is a open-source game-development framework written in the Java and created by Mario Zechner in 2014", "m": ["050e"], "s": ["tb","fm","ps","hd"]},
	{"c": 3, "w": 576, "p": "vulkan", "t":"Vulkan", "d": "is a low-overhead computer graphics API, first announced at GDC 2015 by the Khronos Group", "m": ["035s"], "s": ["tb","fe","ps","hr"]},
	{"c": 8, "w": 576, "p": "cocos2d", "t":"Cocos2D", "d": "is framework for making 2D games and apps, created by Ricardo Quesada in 2008", "m": ["037l"], "s": ["ts","fe","ps","hd"]},
	{"c": 8, "w": 576, "p": "tiled", "t":"Tiled", "d": "is a cross-platform open-source tile map editor for 2D Games, created by Thorbjørn Lindeijer in 2009", "m": ["052m"], "s": ["tb","ps"]},
	{"c": 3, "w": 576, "p": "webgl", "t":"WebGL", "d": "is a JavaScript API for rendering 3D computer graphics, developed by Khronos Group and released in 2011", "m": ["040s"], "s": ["tm","fm","ps","hl"]},
	{"c": 8, "w": 576, "p": "cryengine", "t":"CryEngine", "d": "is a game engine developed by Crytek in the 2002 and it was first used for first-person shooter Far Cry", "m": ["045k"], "s": ["tb","fe","pt","hb"]},
	{"c": 8, "w": 576, "p": "unreal", "t":"Unreal Engine", "d": "is a game engine developed by Epic Games in the 1998 and first used for first-person shooter Unreal", "m": ["051d"], "s": ["tm","fe","ph","hd"], "b": 1},
	{"c": 0, "w": 768, "p": "color", "t":"color", "d": "is CSS1 property specifies the color of text", "m": ["035s"], "s": ["tb","ph"]},
	{"c": 8, "w": 576, "p": "hud", "t":"HUD", "d": "Head-Up Display provides information that you need on the fly for play, including (depending on the game) ammo count, current weapon, health points", "m": ["052m"], "s": ["bb"], "b": 1},
	{"c": 7, "w": 384, "p": "roadmap", "t":"Roadmap", "d": "The project roadmap is a graphical plan that matches short-term and long-term project’s goals", "m": ["035h"], "s": ["tm","fe","ps","hl"]},
	{"c": 7, "w": 384, "p": "cv2K16", "t":"Curriculum vitae 2K16", "d": "My Software Engineer’s Profile <a href='http://exey.ru'>http://exey.ru</a>", "m": ["034m"], "s": ["tm","pt"]},
	{"c": 8, "w": 720, "p": "pokemongo", "t":"Pokémon GO", "d": "is an augmented reality game developed and published by Niantic for mobile devices at 6th of July 2016", "m": ["050e"], "s": ["tb","ps","hd"], "b": 1},
	{"c": 1, "w": 576, "p": "inequality", "t":"Inequality", "d": "is an operator that returns true if the operands are not equal", "m": ["035s"], "s": ["tm","hl"]},
	{"c": 5, "w": 383, "p": "colorpicker", "t":"Color Picker", "d": "is an user interface widget that allows a user to select a color as a hex value", "m": ["034m"], "s": ["tm","pt"], "b": 1},
	{"c": 7, "w": 384, "p": "emailthread", "t":"Email thread", "d": "is an message and a list of all of the subsequent replies pertaining to the original message. Email was invented by Ray Tomlinson in 1972", "m": ["035s"], "s": ["tm","fe","ph","hl"]},
	{"c": 8, "w": 576, "p": "cs", "t":"Counter-Strike", "d": "is modification of Half-Life first-person shooter created by by Minh \"Gooseman\" Le and Jess \"Cliffe\" Cliffe in 1999. The chicken is used as a running gag in CS series", "m": ["035h"], "s": ["ps","fm","bb"]},
	{"c": 2, "w": 461, "p": "417", "t":"417", "d": "is a HTTP Status Code is given when server cannot meet the requirements of the Expect request-header field", "m": ["035h","000p"], "s": ["tb","ph"]},
	{"c": 1, "w": 576, "p": "loop", "t":"Loop", "d": "in Programming is a statement which are used to repeat a block of code", "m": ["035s"], "s": ["tm","fe","ps","hl"]},
	{"c": 8, "w": 576, "p": "outrun", "t":"Out Run", "d": "is an arcade game designed by Yu Suzuki and released by Sega in 1986", "m": ["037l"], "s": ["br","hd"]},
	{"c": 8, "w": 720, "p": "blacksquare", "t":"Black Square", "d": "Unpublished shot inspired by small indie game called Color Geek and developed by me a couple years ago for <a href='http://mozgazm.com/#colorgeek'>iOS and Android</a>", "m": ["044p"], "s": ["tb","fe","ph","hd"]},
	{"c": 3, "w": 576, "p": "fillrect", "t":"fillRect()", "d": "method of the Canvas 2D API draws a “filled” rectangle at (x, y) position and size by (width, height). The rectangle can be masked with a custom shape by other API methods.", "m": ["001b"], "s": ["bb"]},
	{"c": 3, "w": 768, "p": "rigging", "t":"Rigging", "d": "is the process of creating a skeleton that making 3D model able to move, it is usually includes the placement of an underlying bone structure", "m": ["035s"], "s": ["tm","fe","ps","hl"]},
	{"c": 5, "w": 576, "p": "batteryindicator", "t":"Battery Indicator", "d": "is a User Interface that shows charge battery level", "m": ["036h"], "s": ["tm","fe","ps","hb"], "b": 1},
	{"c": 0, "w": 576, "p": "font-stretch", "t":"font-stretch", "d": "is CSS3 property that allows to make text wider or narrower", "m": ["035s"], "s": ["bb","hl"]},
	{"c": 8, "w": 432, "p": "spaceinvaders", "t":"Space Invaders", "d": "is an arcade video game developed by Tomohiro Nishikado and released in 1978", "m": ["037l"], "s": ["ts","fm","ps","hd"]},
	{"c": 4, "w": 384, "p": "details", "t":"details", "d": "is HTML5 tag used for extra details that the user can view or hide on demand", "m": ["036h"], "s": ["tb","fe","ps","hb"]},
	{"c": 0, "w": 720, "p": "overflow", "t":"overflow", "d": "is CSS2 property that specifies what happens if content overflows an element boundaries", "m": ["001b"], "s": ["bb"]},
	{"c": 6, "w": 384, "p": "update2", "t":"UPDATE", "d": "is SQL statement that uses to update existing records in a table", "m": ["049p"], "s": ["tm","fe","ps","hl"]},
	{"c": 4, "w": 720, "p": "kbd", "t":"Keyboard input", "d": "kbd is HTML tag used to define user input that typically entered via keyboard", "m": ["016k"], "s": ["ps"], "b": 1},
	{"c": 0, "w": 384, "p": "transition-property", "t":"transition-property", "d": "is CSS3 property that specifies the name of the property for transition animation", "m": ["048m"], "s": ["tm","fm","ps","hd"]},
	{"c": 1, "w": 768, "p": "override", "t":"Method overriding", "d": "is a programming language feature that allows to replace implementation of a method", "m": ["036h"], "s": ["br"], "b": 1},
	{"c": 1, "w": 403, "p": "monodevelop", "t":"MonoDevelop", "d": "is an open-source cross-platform IDE which appeared in late 2003 and now supports C#/F#, C/C++, Python, D, Java, Vala and other.", "m": ["040s"], "s": ["tm","fm","ps"]},
	{"c": 1, "w": 403, "p": "netbeans", "t":"NetBeans", "d": "is an open-source cross-platform IDE which was developed in 1996 and now supports Java, C/C++, PHP, JavaScript, Scala, Go and other languages via plugins", "m": ["005b"], "s": ["fe","ps","hb"]},
	{"c": 1, "w": 403, "p": "vim", "t":"Vim", "d": "is an open-source cross-platform code editor released in 1991 and it supports almost all programming languages via plugins", "m": ["039b"], "s": ["tm","fe","ph","hd"]},
	{"c": 1, "w": 403, "p": "eclipse", "t":"Eclipse", "d": "is an open-source cross-platform IDE initially released in 2001 and mostly supports Java, but supports more languages like C/C++, PHP, Perl, Ruby and other via plugins", "m": ["016k"], "s": ["fe","br","hr"]},
	{"c": 1, "w": 403, "p": "jedit", "t":"jEdit", "d": "is a free cross-platform code editor which created in 1998 by Slava Pestov and supports Java", "m": ["036h"], "s": ["tb","fe","hb"], "b": 1},
	{"c": 1, "w": 403, "p": "emacs", "t":"Emacs", "d": "is a family of code editors which appeared in 1976 and supports a lot of programming languages", "m": ["001b"], "s": ["tm","fm","br"]},
	{"c": 1, "w": 403, "p": "atom", "t":"Atom", "d": "is an open-source cross-platform text editor which was developed in 2014 by GitHub and supports syntax highlighting of many programming languages", "m": ["047l"], "s": ["ts","fe","ps","hl"]},
	{"c": 1, "w": 403, "p": "notepad++", "t":"Notepad++", "d": "is a free text editor on Windows released in late 2003 and supports syntax highlighting of more than 50 programming languages", "m": ["037l"], "s": ["ts","fe","ps","hd"]},
	{"c": 1, "w": 403, "p": "brackets", "t":"Brackets", "d": "is an open-source cross-platform code editor which created in 2014 and focus on JavaScript, HTML5 and CSS", "m": ["048m"], "s": ["tb","fe","ps","hd"]},
	{"c": 1, "w": 403, "p": "flashdevelop", "t":"FlashDevelop", "d": "is an open-source IDE on Windows which was developed in 2005 by Mika Palmu and Philippe Elsass and supports ActionScript, Haxe and JavaScript", "m": ["023n"], "s": ["tm","fm","ps","hb"]},
	{"c": 1, "w": 403, "p": "xcode", "t":"Xcode", "d": "is free IDE for Mac OS X which was released in 2003 and now supports Xcode supports C/C++, Objective-C/C++, Java, AppleScript, Python, Ruby, Rez, and Swift", "m": ["049p"], "s": ["tb","fe","ps","hl"]},
	{"c": 1, "w": 403, "p": "idea", "t":"Intelij IDEA", "d": "Intelij IDEA (community edition) is open-source cross-platform IDE and supports primarily Java and many other languages via plugins", "m": ["045k"], "s": ["tb","fe","pt","hb"]},
	{"c": 8, "w": 384, "p": "blockade", "t":"Blockade", "d": "is a first game in snake genre developed by Gremlin and published by Sega in October 1976", "m": ["048m"], "s": ["tm","fe","ps","hb"]},
	{"c": 5, "w": 384, "p": "login", "t":"Log in", "d": "this is a process in which user receives access to computer system", "m": ["023n"], "s": ["tm","fe","ps","hb"]},
	{"c": 4, "w": 384, "p": "output", "t":"output", "d": "is HTML tag used in forms, it specifies the result of a calculation", "m": ["005b"], "s": ["bb","hb"]},
	{"c": 8, "w": 461, "p": "donkeykong", "t":"Donkey Kong", "d": "is an arcade game released by Nintendo in 1981", "m": ["016k"], "s": ["ts","fm","ps","hr"], "b": 1},
	{"c": 0, "w": 1024, "p": "max-width", "t":"max-width", "d": "CSS2 property that used to set the maximum width of an element", "m": ["049p"], "s": ["br"], "b": 1},
	{"c": 3, "w": 432 , "p": "stitching", "t":"Image Stitching", "d": "is a practice and algorithm of combining photos with overlapping parts to create high-resolution panorama", "m": ["048m"], "s": ["br"]},
	{"c": 5, "w": 768 , "p": "pulltorefresh", "t":"Pull to Refresh", "d": "is a touch gesture which uses for refresh, it was first introduced by Loren Brichter in the Tweetie app in 2008", "m": ["023n", "022o"], "s": ["ps"]},
	{"c": 8, "w": 432 , "p": "princeofpersia", "t":"Prince of Persia", "d": "is a game created by Jordan Mechner in 1989 originally for Apple II", "m": ["036h"], "s": ["tm","fe","ps","hb"]},
	{"c": 6, "w": 864 , "p": "redis-expire", "t":"Redis’s EXPIRE", "d": "Redis \"expire\" command sets a timeout in seconds on key", "m": ["005b"], "s": ["tm","fm","ps","hb"]},
	{"c": 5, "w": 768 , "p": "bookmark", "t": "Bookmark", "d": "is a saved link to website", "m": ["016k"], "s": ["br"]},
	{"c": 2, "w": 827 , "p": "450", "t": "450", "d": "is a HTTP Status Code is given when webpage blocked by Windows Parental Controls", "m": ["023n"], "s": ["tm","ps"]},
	{"c": 0, "w": 384 , "p": "text-align", "t": "text-align", "d": "CSS1 property that sets the horizontal alignment of text in an element", "m": ["016k"], "s": ["ts","fe","ps","hr"]},
	{"c": 5, "w": 432 , "p": "saveas", "t": "Save As…", "d": "allows to save your file with a different name", "m": ["047l"], "s": ["br"]},
	{"c": 5, "w": 384 , "p": "cut", "t": "Cut", "d": "is the computer command that removes the selected content and copy it to clipboard. First time was implemented by Larry Tesler in 1974 at Xerox PARC", "m": ["047l"], "s": ["ts","fe","ps","hl"]},
	{"c": 8, "w": 576 , "p": "alleycat", "t": "Alley Cat", "d": "is a arcade game created by Bill Williams for the Atari 8-bit in 1983", "m": ["047l"], "s": ["bb","hl"]},
	{"c": 0, "w": 432 , "p": "letter-spacing", "t": "letter-spacing", "d": "is CSS 1 property controls the amount of space between each letter in a given element or block of text", "m": ["043b"], "s": ["tb","fe","ps","hb"]},
	{"c": 0, "w": 432 , "p": "word-wrap", "t": "word-wrap", "d": "is CSS 3 property that used to be able to break long words and wrap onto the next line", "m": ["043b"], "s": ["bb","hb"]},
	{"c": 8, "w": 576 , "p": "pong", "t": "Pong", "d": "is an arcade tennis-like game for two players developed by Allan Alcorn in Atari and released in 1972", "m": ["044p"], "s": ["tb","fe","ph","hd"], "b": 1},
	{"c": 7, "w": 384 , "p": "hashtag", "t":"Hashtag", "d": "is word prefixed with the # character. First became popular in IRC networks to mark topics, and second in 2007 year when Nate Ritter used it during #sandiegofire in Twitter", "m": ["047l"], "s": ["ts","fm","ps"]},
	{"c": 7, "w": 384 , "p": "heatmap", "t": "Heatmap", "d": "is a visualization of table of numbers, first time was used by microbiologist by Peter Sneath in 1957", "m": ["046n"], "s": ["tm","fe","ps","hl"]},
	{"c": 1, "w": 407 , "p": "elixir", "t": "Elixir", "d": "is an open source functional programming language built atop the Erlang Virtual Machine and created by José Valim in 2012", "m": ["040s"], "s": ["tm","ps","hl"]},
	{"c": 1, "w": 407 , "p": "go", "t": "Go", "d": "is an open source, compiled programming language created by Google in 2009", "m": ["045k"], "s": ["tb","fe","pt","hb"]},
	{"c": 1, "w": 407 , "p": "factor", "t": "Factor", "d": "is a stack-oriented programming language created by Slava Pestov in 2003", "m": ["044p"], "s": ["tb","fm","ph"], "b": 1},
	{"c": 1, "w": 408 , "p": "whitespace", "t": "Whitespace", "d": "is an esoteric programming language created by Edwin Brady and Chris Morris in 2003. Language uses only whitespace as syntax", "m": ["039b"], "s": ["tm","fe","ps","hd"]},
	{"c": 1, "w": 407 , "p": "hack", "t": "Hack", "d": "is an open-source programming language for the HipHop Virtual Machine (HHVM), created by Facebook and released in 2014 year", "m": ["043b"], "s": ["tb","fe","ps","hd"]},
	{"c": 1, "w": 407 , "p": "clojure", "t": "Clojure", "d": "is a dialect of the Lisp programming language created by Rich Hickey and released in 2007 year", "m": ["041v"], "s": ["ts","fe","ps","hl"]},
	{"c": 1, "w": 408 , "p": "haxe", "t": "Haxe", "d": "is an open source programming language + cross-compiler which can produce native applications for Mobile/Web/Desktop platforms. Released in 2005 year", "m": ["035s"], "s": ["tm","fm","ps"]},
	{"c": 1, "w": 407 , "p": "d", "t": "D", "d": "is an object-oriented programming language created by Andrei Alexandrescu and Walter Bright and released in 2001 year", "m": ["001b"], "s": ["tm","fm"]},
	{"c": 1, "w": 408 , "p": "scala", "t": "Scala", "d": "is an object-functional programming language created by Martin Odersky and released in 2003 year", "m": ["036h"], "s": ["tb","fe","ps","hd"]},
	{"c": 1, "w": 408 , "p": "swift", "t": "Swift", "d": "is a programming language created by Apple and released in 2014 year", "m": ["042m"], "s": ["tb","fm","pt","hl"]},
	{"c": 1, "w": 407 , "p": "fsharp", "t": "F#", "d": " is an open source functional-first programming language developed by Microsoft and released in 2005 year", "m": ["046n"], "s": ["fe","br","hl"]},
	{"c": 1, "w": 407 , "p": "typescript", "t": "TypeScript", "d": "is an open source programming language developed by Microsoft and released in 2012 year", "m": ["037l"], "s": ["ts","fe","ps","pd"], "b": 1},
	{"c": 5, "w": 569 , "p": "toast", "t": "Toast", "d": "Toast notification is a user interface element used to display brief information", "m": ["044p"], "s": ["tb","ph"], "b": 1},
	{"c": 1, "w": 768 , "p": "touch", "t": "touch", "d": "is linux/unix shell command that creates new files", "m": ["046n"], "s": ["tb","fe","hl"]},
	{"c": 1, "w": 576 , "p": "cd", "t": "cd", "d": "is linux/unix shell command that changes the current directory", "m": ["045k"], "s": ["tb","fe","hb"], "b": 1},
	{"c": 1, "w": 384 , "p": "killall", "t": "killall", "d": "is linux/unix shell command that kills all process with a particular name", "m": ["046n"], "s": ["tm","fm","ps"]},
	{"c": 1, "w": 384 , "p": "tail", "t": "tail", "d": "is linux/unix shell command that prints the last part of file, last 10 lines", "m": ["045k"], "s": ["tb","pt"]},
	{"c": 5, "w": 576 , "p": "button", "t": "The Button", "d": "is a basic UI element of computer programs that allows user to trigger an event, interact or confirming an action", "m": ["044p"], "s": ["bb"]},
	{"c": 5, "w": 514 , "p": "checkbox", "t": "The CheckBox", "d": "is UI control allows the user to set YES (checked) or NO (not checked) on a simple yes/no question", "m": ["043b"], "s": ["tb","fe","ps","hd"]},
	{"c": 6, "w": 384 , "p": "droptable", "t": "DROP TABLE", "d": "is SQL statement that removes a table", "m": ["042m"], "s": ["tb","pt"]},
	{"c": 6, "w": 384 , "p": "createtable", "t": "CREATE TABLE", "d": "is SQL statement that creates a table in a database", "m": ["042m"], "s": ["tm","fe","pt","hl"]},
	{"c": 6, "w": 384 , "p": "delete", "t": "DELETE", "d": "is SQL statement that removes one or more records from a table", "m": ["042m"], "s": ["bb","hl"]},
	{"c": 6, "w": 384 , "p": "altertable", "t": "ALTER TABLE", "d": "is SQL statement that adds or modifies columns in an existing table", "m": ["042m"], "s": ["tm","fe","pt","hl"]},
	{"c": 3, "w": 576 , "p": "jpg", "t":"JPEG", "d": "JPEG is a lossy image compression standard since 1992. Compression works by applying discrete cosine transforms by dividing picture into blocks of 8x8 pixels", "m": ["037l"], "s": ["fe","br","hd"]},
	{"c": 8, "w": 864 , "p": "pacman", "t":"wanna et ur cherry lik im pcman", "d": "Pac-Man is an arcade game developed by Namco and released in 1980", "m": ["037l", "038g"], "s": []},
	{"c": 2, "w": 768 , "p": "400", "t":"400", "d": "The 400 Bad Request HTTP status means that the request you sent to the server was incorrect", "m": ["039b"], "s": ["bb"], "b": 1},
	{"c": 2, "w": 398 , "p": "redirect", "t":"Redirect", "d": "The 301 HTTP status code means that a page has permanently moved to a new location", "m": ["039b"], "s": ["tm","ps"]},
	{"c": 2, "w": 864 , "p": "exception", "t":"Exception", "d": "is a problem that arises during the execution of a program", "m": ["039b"], "s": ["tm","ps"]},
	{"c": 1, "w": 1024, "p": "split", "t":"String.split()", "d": " method is used to split a string into an array of substrings", "m": ["039b"], "s": ["fe","ps","hd"]},
	{"c": 5, "w": 864 , "p": "meme", "t":"Meme", "d": "Dog picture is drawn by Pavel Durov(creator of VK.com, second largest social network in EU) as fork of Advice Dog meme", "m": ["039b"], "s": ["ps"]},
	{"c": 1, "w": 392 , "p": "opensource", "t":"Open Source", "d": "In opposition to proprietary CodeBabes, I open free CodeBodies.com", "m": ["039b"], "s": ["tm","fe","ph","hd"]},
	{"c": 8, "w": 375 , "p": "flappybird", "t":"Flappy Bird", "d": "is a mobile game developed by Vietnam indie developer Dong Nguyen", "m": ["037l"], "s": ["br","hd"]},
	{"c": 8, "w": 407 , "p": "quake", "t":"Quake", "d": "Quake III Arena is a first-person shooter game developed by id Software in 1999 year", "m": ["037l"], "s": ["ts","fm","ps","hd"]},
	{"c": 5, "w": 835 , "p": "sharing", "t":"Sharing", "d": "is the practice of distributing or providing access to digitally information", "m": ["036h"], "s": ["tb","ps","hd"]},
	{"c": 8, "w": 768 , "p": "fruitninja", "t":"Fruit Ninja", "d": "is mobile game controlled via touch pad where player slices fruits with a blade. Game was released in 2010", "m": ["036h"], "s": ["tb","ps","hd"], "b": 1},
	{"c": 8, "w": 768 , "p": "gamepad", "t":"Game Pad", "d": "is a game controlling device for two hands designed to be connected to a computer or console gaming system. Idea by Bonsoir Mademoiselle", "m": ["036h"], "s": ["bb"]},
	{"c": 5, "w": 432 , "p": "widget", "t":"Widget", "d": "Android Widgets are miniature application views that can be embedded in other applications (for example the Home screen)", "m": [], "s": ["tb","ps"]},
	{"c": 5, "w": 787 , "p": "hardwarenavkeys", "t":"Hardware Navigation Keys ", "d": "Most Android phones have physical navigation keys, such as Menu, Back and Search", "m": ["035s"], "s": ["br"]},
	{"c": 5, "w": 442 , "p": "recentappslist", "t":"Recent Apps List", "d": "You can jump instantly from one task to another using the Android multitasking UI called Recent Apps List", "m": ["035s"], "s": ["tb","ps"]},
	{"c": 5, "w": 864 , "p": "slidingmenu", "t":"Sliding Menu", "d": "Android sliding panel menu used to navigate between major modules of the application", "m": ["036h"], "s": ["tb","ps","hd"]},
	{"c": 5, "w": 436 , "p": "actionbar", "t":"Action Bar", "d": "Android Action Bar is located at the top of the Activity and displays the title, icon, actions which can be triggered, also it can be used for navigation in your application", "m": ["035s", "000p"], "s": ["tb","ps"]},
	{"c": 5, "w": 821 , "p": "fragments", "t":"Fragments", "d": "Android Fragment represents a behavior or a portion of UI in an Activity. It can be combines multiple fragments in a single activity to build a multi-pane UI", "m": ["035s", "036h"], "s": ["tb","ps"]},
	{"c": 4, "w": 1023, "p": "input2", "t":"Input", "d": "is HTML tag used for forms, it can be a text field, a checkbox and more. Remake of input 2009", "m": ["035s"], "s": ["tb","ps"], "b": 1},
	{"c": 1, "w": 407 , "p": "erlang", "t":"Erlang", "d": "is a functional, compiled programming language. Created in 1986 by Joe Armstrong and was used within the company Ericsson, became open-source in 1998", "m": ["027s"], "s": ["tb","fe","ps","hr"], "b": 1},
	{"c": 1, "w": 407 , "p": "python", "t":"Python", "d": "is an object-oriented, interpreted programming language. Created by Guido van Rossum in 1991 and named after \"Monty Python's Flying Circus\"", "m": ["027s"], "s": ["tb","fe","ps","hd"]},
	{"c": 1, "w": 407 , "p": "objc", "t":"Objective C", "d": "is an object-oriented, compiled programming language used by Apple, based on the C language. Created by Brad Cox in early 1983", "m": ["027s"], "s": ["tb","pt","hd"]},
	{"c": 1, "w": 407 , "p": "ruby", "t":"Ruby", "d": "is an object-oriented, functional programming language. Created by Yukihiro Matsumoto in 1995 year, semantics, syntax and idea of ​​the name is borrowed from Perl", "m": ["027s"], "s": ["tb","pt"]},
	{"c": 1, "w": 407 , "p": "java", "t":"Java", "d": "is an object-oriented, compiled programming language developed by James Gosling for Sun in 1995 year and was initially targeted for home appliances", "m": ["027s"], "s": ["tb","fe","pt","hr"]},
	{"c": 1, "w": 407 , "p": "csharp", "t":"C#", "d": "is an object-oriented compiled programming language. Developed in 2000 year under the leadership of Anders Hejlsberg at Microsoft", "m": ["027s"], "s": ["tb","fe","hr"]},
	{"c": 1, "w": 407 , "p": "js", "t":"Queen of the Web", "d": "JavaScript is a prototype-oriented programming language. Created in 1995 by Brendan Eich for Netscape Navigator", "m": ["027s"], "s": ["tb","fe","pt","hr"]},
	{"c": 1, "w": 407 , "p": "nasm", "t":"NASM", "d": "is a free assembler for architecture x86, created by Simon Tatham and Julian Hall in 1996 year", "m": ["027s"], "s": ["tb","pt","hd"], "b": 1},
	{"c": 1, "w": 407 , "p": "c", "t":"C", "d": "is an procedural, compiled programming language​. Created by Dennis Ritchie and Ken Thompson and released in 1972", "m": ["027s"], "s": ["tb","fe","hr"]},
	{"c": 1, "w": 407 , "p": "perl", "t":"Perl", "d": "is a functional programming language created by Сanadian-born programmer and linguist Larry Wall in 1987", "m": ["027s"], "s": ["tb","pt","hd"]},
	{"c": 1, "w": 407 , "p": "php", "t":"PHP", "d": "is an object-oriented, interpreted programming language created based on Perl by the Danish programmer Rasmus Lerdorf, and released in 1994", "m": ["027s"], "s": ["tb","pt","hd"]},
	{"c": 1, "w": 407 , "p": "cpp", "t":"C++", "d": "is an object-oriented, compiled programming language. An early version of the language (\"C with classes\") released in 1980 by Bjorn Stroustrup", "m": ["027s"], "s": ["tb","fe","pt","hr"]},
	{"c": 5, "w": 768 , "p": "tap", "t":"tap", "d": "Multi-touch gesture. Uses for pointing an element", "m": ["034m"], "s": ["pt"]},
	{"c": 5, "w": 432 , "p": "scroll", "t":"scroll", "d": "Multi-touch gesture. Uses for scrolling content", "m": ["034m"], "s": ["tm","hd"]},
	{"c": 5, "w": 857 , "p": "zoom", "t":"zoom", "d": "Multi-touch gesture. Uses for for scale an element", "m": ["034m"], "s": ["tm","pp"]},
	{"c": 5, "w": 660 , "p": "pinch4", "t":"4 finger pinch", "d": "Multi-touch gesture. Uses on iPad for revert to home", "m": ["034m"], "s": ["tm"]},
	{"c": 5, "w": 598 , "p": "taphold", "t":"tap and hold", "d": "Multi-touch gesture. Uses for showing for more options", "m": ["034m"], "s": ["tm","br"], "b": 1},
	{"c": 5, "w": 602 , "p": "swipe", "t":"swipe", "d": "Multi-touch gesture. Allows flip through parts of large content", "m": ["034m"], "s": ["tr","pt"]},
	{"c": 5, "w": 576 , "p": "rotate", "t":"rotate", "d": "Multi-touch gesture. Allows rotate clockwise or counterclockwise an element", "m": ["034m"], "s": ["br"]},
	{"c": 5, "w": 432 , "p": "facepalm", "t":"Facepalm", "d": "Physical gesture. Popular in web for display a frustration", "m": ["034m"], "s": ["tm","fm","pt","hd"]},
	{"c": 4, "w": 384 , "p": "video", "t":"HTMLVideoElement", "d": "HTML5 tag. Defines a video content", "m": ["033m"], "s": ["tb","fe","ps","hl"], "b": 1},
	{"c": 4, "w": 384 , "p": "audio", "t":"HTMLAudioElement", "d": "HTML5 tag. Defines a audio content", "m": ["033m"], "s": ["tb","fe","ps","hl"]},
	{"c": 4, "w": 864 , "p": "body", "t":"body", "d": "Defines a container for all content of the HTML document", "m": ["031y", "032c"], "s": ["tm","fe","pp","hb","hl"]},
	{"c": 4, "w": 864 , "p": "header", "t":"header", "d": "is HTML5 tag that defines a header for a HTML document", "m": ["031y", "032c"], "s": ["tm","fe","pp","hb","hl"]},
	{"c": 4, "w": 864 , "p": "nav", "t":"nav", "d": "is HTML5 tag that defines a section of navigation links", "m": ["031y", "032c"], "s": ["tm","fe","pp","hb","hl"]},
	{"c": 4, "w": 864 , "p": "meter", "t":"meter", "d": "is HTML5 tag that defines a measurement", "m": ["031y", "032c"], "s": ["tm","fe","pp","hb","hl"]},
	{"c": 4, "w": 864 , "p": "article", "t":"article", "d": "is HTML5 tag that defines a independent or external content", "m": ["031y", "032c"], "s": ["pp","br"]},
	{"c": 4, "w": 864 , "p": "aside", "t":"aside", "d": "is HTML5 tag that defines some content aside from the main page", "m": ["031y", "032c"], "s": ["tm","fe","hl"]},
	{"c": 4, "w": 576 , "p": "progress", "t":"progress", "d": "is HTML5 tag which represents the progress", "m": ["031y", "032c"], "s": ["tm","fe","br","hb","hl"]},
	{"c": 4, "w": 864 , "p": "canvas", "t":"canvas", "d": "is HTML5 tag which used to draw graphics", "m": ["031y", "032c"], "s": ["tm","fe","pt","hb","hl"]},
	{"c": 4, "w": 432 , "p": "u", "t":"Zombie Tag", "d": "tag was killed in HTML 4.01 but reanimated in HTML5, use it for underlined text", "m": ["030a"], "s": ["tm","fe","pp","hl"]},
	{"c": 5, "w": 576 , "p": "like", "t":"Like", "d": "is a feature of Facebook, which allow user to express that he or she likes it", "m": ["029v"], "s": ["tb","ps"], "b": 1},
	{"c": 5, "w": 576 , "p": "instagram", "t":"instagram", "d": "is a photo sharing social service and mobile app", "m": ["029v"], "s": ["tb","ps"]},
	{"c": 5, "w": 440 , "p": "tweet", "t":"Tweet", "d": "is a message sent using Twitter", "m": ["029v"], "s": ["tb","ps"]},
	{"c": 5, "w": 622 , "p": "checkin", "t":"Check-in", "d": "is geo social service feature (Foursquare, Google Latitude, …)", "m": ["029v"], "s": ["tb","ps"], "b": 1},
	{"c": 5, "w": 399 , "p": "pin", "t":"Pin", "d": "is a picture on content sharing service Pinterest", "m": ["029v"], "s": ["tb","ps"]},
	{"c": 5, "w": 576 , "p": "rss", "t":"RSS", "d": "is a web feed formats used to publish news entries in unified XML-based format", "m": ["029v"], "s": ["tb","ps"]},
	{"c": 4, "w": 1024, "p": "html5", "t":"HTML5", "d": "", "m": ["028a"], "s": ["ts","fe","hd"]},
	{"c": 6, "w": 864 , "p": "mongodb-where", "t":"MongoDB's WHERE", "d": "MongoDB is a NoSQL database where queries, performed with the find()", "m": ["024n"], "s": ["pt"]},
	{"c": 0, "w": 864 , "p": "lineheight", "t":"line-height", "d": "CSS 1 property that defines the line height", "m": ["024n"], "s": ["ts","pt"]},
	{"c": 0, "w": 864 , "p": "pseudolink", "t":":link", "d": "CSS pseudo class defines a style of the unvisited links", "m": ["024n"], "s": ["pp"]},
	{"c": 0, "w": 864 , "p": "pseudoactive", "t":":active", "d": "CSS pseudo class defines a style of the active links", "m": ["024n"], "s": ["pp"]},
	{"c": 5, "w": 576 , "p": "cloudstorage", "t":"Cloud Storage", "d": "is a model in which data is stored remotely and made available via internet", "m": ["024n"], "s": ["ts","fe","hl"]},
	{"c": 5, "w": 911 , "p": "qrcode", "t":"QR code", "d": "Quick Response Code was invinted in Japan by Denso Wave in 1994", "m": ["024n"], "s": ["br"]},
	{"c": 4, "w": 864 , "p": "head", "t":"head", "d": "is a HTML tag that contains information about the document", "m": ["024n"], "s": ["tb","fe","pt","hd"]},
	{"c": 4, "w": 864 , "p": "title", "t":"title", "d": "is a HTML tag that defines the title of the document", "m": ["027s"], "s": ["tb","fe","hd"]},
	{"c": 4, "w": 864 , "p": "link", "t":"link", "d": "is a HTML tag that mostly used for link the stylesheet", "m": ["027s"], "s": ["tb","fe","hd"]},
	{"c": 4, "w": 576 , "p": "meta", "t":"meta", "d": "is a HTML tag that handle metadata (description, keywords) of document", "m": ["027s"], "s": ["tb","fe","hd"]},
	{"c": 4, "w": 576 , "p": "headclose", "t":"/head", "d": "is a end HTML tag of head container", "m": ["027s"], "s": ["tb","hd"]},
	{"c": 4, "w": 864 , "p": "script", "t":"script", "d": "is a HTML tag that defines client-side script, generally JavaScript", "m": ["027s"], "s": ["tb","fe","hd"]},
	{"c": 2, "w": 432 , "p": "xmlencryption", "t":"XML Encryption", "d": "security vulnerability was found at the end of 2011", "m": ["026v"], "s": ["tm","fm","pp","hr"]},
	{"c": 7, "w": 864 , "p": "ppa", "t":"Pay Per Action", "d": "Most effective model of affiliate programs, the advertiser pays for action of user", "m": ["026v"], "s": ["tb","br","hr"]},
	{"c": 7, "w": 864 , "p": "ppv", "t":"Pay Per View", "d": "The advertiser pays per view ad by user", "m": ["026v"], "s": ["tb","pp"]},
	{"c": 7, "w": 384 , "p": "ppd", "t":"Pay Per Download", "d": "The advertiser pays for visitors who download something", "m": ["026v"], "s": ["pp","br","hr"]},
	{"c": 7, "w": 576 , "p": "ppc", "t":"Pay Per Click", "d": "The advertiser pays the owners of the site for users clicks on the banner", "m": ["026v"], "s": ["tb","ps"]},
	{"c": 3, "w": 576 , "p": "gif", "t":"GIF89a", "d": "GIF can be animated", "m": ["026v"], "s": ["tb","pp"]},
	{"c": 3, "w": 576 , "p": "png", "t":"PNG 32-bit RGBA", "d": "PNG supports a full alpha channel", "m": ["026v"], "s": ["tb","pt"], "b": 1},
	{"c": 8, "w": 576 , "p": "omnom", "t":"Om Nom", "d": "Main hero of Cut the Rope game", "m": ["001b"], "s": ["tm","pp"]},
	{"c": 8, "w": 766 , "p": "redbirdandpiglet", "t":"The Red Bird and The Piglet", "d": "Basic characters of Angry Birds", "m": ["001b", "022o"], "s": ["tm"], "b": 1},
	{"c": 7, "w": 535 , "p": "cv", "t":"Curriculum vitae", "d": "", "m": ["025d"], "s": ["tm","ps"]},
	{"c": 0, "w": 576 , "p": "borderradius", "t":"border-radius", "d": "CSS3 property. Specifies roundness corners of the element", "m": ["025d"], "s": ["tb","pp"]},
	{"c": 8, "w": 432 , "p": "level", "t":"Level up", "d": "", "m": ["025d"], "s": ["tb","ps"]},
	{"c": 1, "w": 768 , "p": "proxy", "t":"Proxy", "d": "is a software design pattern", "m": ["016k"], "s": ["pt"]},
	{"c": 8, "w": 768 , "p": "help", "t":"Help!", "d": "Tentacles Defense's inspired shot", "m": ["023n"], "s": ["ts","fe","pt","hb"]},
	{"c": 0, "w": 768 , "p": "inline", "t":"inline", "d": "CSS 1 Property. Generates an inline box, with no line break before or after the element", "m": ["023n"], "s": ["tm","pt","hb"]},
	{"c": 0, "w": 918 , "p": "margin", "t":"margin", "d": "CSS 1 Shorthand Property. Specifies the margin for all four sides: top, right, bottom and left", "m": ["023n"], "s": ["tm","fe","pt","hb"]},
	{"c": 0, "w": 864 , "p": "outlineoffset", "t":"outline-offset", "d": "CSS3 Property. Offsets and draws outline beyond the border edge", "m": ["023n"], "s": ["pp"]},
	{"c": 0, "w": 432 , "p": "verticalalign", "t":"vertical-align", "d": "CSS 1 Property. Specifies the vertical alignment of an element", "m": ["023n"], "s": ["ts","hb"]},
	{"c": 0, "w": 768 , "p": "before", "t":"before", "d": "CSS 2 Selector. Inserts content before the selected element", "m": ["023n"], "s": ["pt"]},
	{"c": 0, "w": 768 , "p": "position", "t":"position", "d": "CSS2 Property. Specifies the type of positioning method used for an element: absolute, relative, static or fixed", "m": ["023n"], "s": ["fe","br","hb"]},
	{"c": 5, "w": 432 , "p": "wall", "t": "The Wall", "d": "", "m": ["023n"], "s": ["tm","fm","pt"]},
	{"c": 5, "w": 768 , "p": "circles", "t":"The Circles", "d": "", "m": ["001b"], "s": ["tm"]},
	{"c": 5, "w": 768 , "p": "copypaste", "t":"Copy-paste", "d": "", "m": ["001b", "024n"], "s": ["ts","tb","pp"], "b": 1},
	{"c": 5, "w": 768 , "p": "progressbar", "t":"Progress bar", "d": "Loading…", "m": ["001b", "024n"], "s": ["ts","tb","pp"], "b": 1},
	{"c": 5, "w": 768 , "p": "2d3d", "t":"2D-3D", "d": "", "m": ["001b", "024n"], "s": ["ts","tb","pp"]},
	{"c": 5, "w": 432 , "p": "tableview", "t":"Table view", "d": "Always provide feedback when users select a list item", "m": ["023n"], "s": ["tm","fe","pp","hb"]},
	{"c": 5, "w": 768 , "p": "alert", "t":"Alert", "d": "Be sure to test the appearance of your alert in both orientations", "m": ["023n"], "s": ["fe","pp","hb"]},
	{"c": 5, "w": 432 , "p": "segmentedcontrol", "t":"Segmented Control", "d": "Make sure that each segment is easy to tap", "m": ["023n"], "s": ["tm","pp"]},
	{"c": 5, "w": 432 , "p": "actionsheet", "t":"Action Sheet", "d": "On iPhone, include a Cancel button", "m": ["023n"], "s": ["tm","fe","pp","hb"]},
	{"c": 5, "w": 432 , "p": "multitasking", "t":"Multitasking", "d": "Ensure that your audio behaves appropriately", "m": ["023n"], "s": ["tm","fe","pt","hb"]},
	{"c": 5, "w": 432 , "p": "timepicker", "t":"Time picker", "d": "On iPad, present a date and time picker only within a popover", "m": ["023n"], "s": ["fe","br","hb"]},
	{"c": 7, "w": 768 , "p": "facebookcredits", "t":"Strip for the Farmville Cash", "m": ["022o"], "s": ["pp"]},
	{"c": 4, "w": 576 , "p": "iframe", "t":"iframe", "d": "is HTML tag that adds an inline frame of web document into the body of current web page", "m": ["021k"], "s": ["tm"]},
	{"c": 5, "w": 768 , "p": "radiobutton", "t":"Radio button", "d": "is a user interface element, which allows user to choose only one option from a group", "m": ["020l"], "s": ["br","hd"]},
	{"c": 4, "w": 768 , "p": "br", "t":"line break", "d": "br is HTML tag that inserts a line break", "m": ["020l"], "s": ["ps"]},
	{"c": 2, "w": 768 , "p": "serverisdown", "t":"The Server Is Down", "d": "503 is HTTP status code says the server is not available", "m": ["0201"], "s": ["fe","br","hd"], "b": 1},
	{"c": 11, "w": 432 , "p": "array", "t":"array", "d": "is a data structure consisting of a list of elements with integer indices", "m": ["020l"], "s": ["ts","fe","hd"]},
	{"c": 4, "w": 569 , "p": "table", "t":"table", "d": "is HTML tag defines a table", "m": ["020l"], "s": ["ts","br","hr"]},
	{"c": 5, "w": 768 , "p": "searchbox", "t":"Search Box", "d": "", "m": ["016k"], "s": ["ph"], "b": 1},
	{"c": 5, "w": 663 , "p": "thebestapp", "t":"The Best App", "d": "Can you find this in the App Store?", "m": ["001b"], "s": ["tm"]},
	{"c": 0, "w": 576 , "p": "display", "t":"display", "d": "CSS 1 property. Defines the type of box an element should generate", "m": ["016k"], "s": ["ph"]},
	{"c": 0, "w": 753 , "p": "cursor", "t":"cursor", "d": "CSS 2 property. Defines the type of cursor to be displayed when pointing on an element", "m": ["016k"], "s": ["pp"]},
	{"c": 2, "w": 493 , "p": "iphonenoflash", "t":"No Flash, no party", "d": "iOS still do not support Flash Player", "m": ["016k"], "s": ["ts","ph"]},
	{"c": 5, "w": 767 , "p": "videoplayer", "t":"Videoplayer", "d": "", "m": ["019z"], "s": ["tm"], "b": 1},
	{"c": 4, "w": 572 , "p": "span", "t":"Span", "d": "is HTML tag for grouping inline elements", "m": ["019z"], "s": ["pt"]},
	{"c": 1, "w": 768 , "p": "singleton", "t":"Singleton", "d": "is a software design pattern", "m": ["019z"], "s": ["tm"]},
	{"c": 1, "w": 904 , "p": "event", "t":"How to subscribe to an event", "d": "Event listener is a function that executes in response to specific event", "m": ["017d","018p"], "s": ["ts"]},
	{"c": 5, "w": 768 , "p": "scrollbar", "t":"Scrollbar", "d": "is a user interface element for continuous content", "m": ["016k"], "s": ["ph"], "b": 1},
	{"c": 4, "w": 472 , "p": "italic", "t":"Italic", "d": "i is HTML tag that defines italic text", "m": ["016k"], "s": ["ts"]},
	{"c": 0, "w": 795 , "p": "nostyle", "t":"Strip down this page", "d": "You can undress the web page at any time", "m": ["016k"], "s": ["ts","fe","ph","hd"], "b": 1},
	{"c": 4, "w": 789 , "p": "style", "t":"Style", "d": "defines style(CSS) for a HTML document", "m": ["003g"], "s": ["fe","hl"]},
	{"c": 4, "w": 768 , "p": "bold", "t":"Bold", "d": "is HTML tag that defines bold text", "m": ["007c"], "s": ["pp","br"]},
	{"c": 1, "w": 704 , "p": "regexp", "t":"How to find a two-letter word?", "d": "The answer is Using Regular Expressions", "m": ["007c"], "s": ["tm"]},
	{"c": 4, "w": 768 , "p": "p", "t":"Paragraph", "d": "p is HTML tag that defines a paragraph", "m": ["007c"], "s": ["ps"]},
	{"c": 6, "w": 505 , "p": "sql", "t":"SQL query to find an ideal girl", "d": "", "m": ["015t"], "s": ["tm","pt"]},
	{"c": 4, "w": 635 , "p": "small", "t":"Size doesn't have a right to be assigned in the markup, but…", "d": "small is HTML tag to define small text", "m": ["014k"], "s": ["ts","pp"]},
	{"c": 1, "w": 768 , "p": "displayobjectcontainer", "t":"Where to add a child?", "d": "DisplayObjectContainer can contain multiple DisplayObject's", "m": ["013k"], "s": ["pp"]},
	{"c": 4, "w": 400 , "p": "a", "t":"Hyperlink", "d": "a is HTML tag to define hyperlinks and anchors", "m": ["012u", "001b"], "s": ["ps"], "b": 1},
	{"c": 1, "w": 726 , "p": "getpixel32", "t":"How to get color of pixel?", "d": "getPixel32(x, y) is ActionScript method that returns an ARGB color value of pixel", "m": ["001b"], "s": ["tm"]},
	{"c": 2, "w": 576 , "p": "exit", "t":"Exit", "d": "Do you want to convert from Windows User to Linux for example?", "m": ["011d"], "s": ["fe","hd"]},
	{"c": 2, "w": 743 , "p": "save", "t":"Save", "d": "", "m": ["011d"], "s": ["fe","hd"]},
	{"c": 2, "w": 768 , "p": "update", "t":"Update", "d": "", "m": ["011d"], "s": ["fm","hd"]},
	{"c": 4, "w": 617 , "p": "time", "t":"TIME is running out faster than he", "d": "time is new HTML5 tag, that defines time or date or both", "m": ["007c", "010r"], "s": ["tm","hr"]},
	{"c": 1, "w": 862 , "p": "mvc", "t":"Model-View-Controller", "d": "MVC is a software design pattern", "m": ["009g"], "s": ["fe","hb"]},
	{"c": 5, "w": 783 , "p": "combobox", "t":"Combo box", "d": "is a user interface element, this is advanced Drop-down list", "m": ["008z"], "s": ["tb","hl"], "b": 1},
	{"c": 4, "w": 476 , "p": "div", "t":"Put your content into DIVs not in TABLEs", "d": "div is HTML tag defines a logical block of content", "m": ["001b"], "s": ["tm","hb"]},
	{"c": 4, "w": 795 , "p": "input", "t":"Input", "d": "is HTML tag used for forms, it can be a text field, a checkbox and more", "m": ["007c"], "s": ["pt"]},
	{"c": 4, "w": 787 , "p": "hr", "t":"Horizontal rule", "d": "hr is HTML tag that creates a horizontal line", "m": ["007c"], "s": ["pt"]},
	{"c": 4, "w": 993 , "p": "img", "t":"Put your image here", "d": "img is HTML tag that embeds an image in a web page", "m": ["006b"], "s": ["ps"]},
	{"c": 3, "w": 432 , "p": "normalmap", "t":"Normal map", "d": "It's need to add details on 3d mesh without using more polygons", "m": ["005b"], "s": ["tm","fm","ps","hr"]},
	{"c": 3, "w": 664 , "p": "emitter", "t":"Emitter", "d": "Source of particles in 3D space", "m": ["005b"], "s": ["tm","fe","br","hr"]},
	{"c": 3, "w": 576 , "p": "lsystem", "t":"L-system", "d": "Lindenmayer system is recursive technique for describing natural-looking organic forms", "m": ["005b"], "s": ["br","hr"]},
	{"c": 3, "w": 768 , "p": "framerate", "t":"Frame rate", "d": "Measurement of frame frequency", "m": ["005b"], "s": ["tm"]},
	{"c": 3, "w": 768 , "p": "baked", "t":"Baked texture map", "d": "Baking is creating textures based on an object’s appearance in the rendered scene", "m": ["005b"], "s": ["br"]},
	{"c": 1, "w": 767 , "p": "flex", "t":"Flex layout containers", "d": "HBox and VBox are layout containers in Flex Framework", "m": ["005b"], "s": ["tm","fe","ps","hr"]},
	{"c": 2, "w": 442 , "p": "itchrist", "t":"ITChrist", "d": "17 April, 2009 four operators of The Pirate Bay were convicted by Stockholm district court", "m": ["004b"], "s": ["hb"]},
	{"c": 1, "w": 658 , "p": "import", "t":"import libraries", "d": "This syntax is used for import libraries in Java and ActionScript", "m": ["003g"], "s": ["hb"]},
	{"c": 0, "w": 772 , "p": "float", "t":"float", "d": "CSS 1 property. Specifies if an element should float towards the left or right margin", "m": ["001b"], "s": ["tm"]},
	{"c": 0, "w": 615 , "p": "list-style-type", "t":"list-style-type", "d": "CSS 1 property. Specifies the style of the bullet", "m": ["002b"], "s": ["fe", "hb"]},
	{"c": 0, "w": 696 , "p": "z-index", "t":"z-index", "d": "CSS 2 Property. Specifies the stacking order of the element relative to other layers", "m": ["002b"], "s": ["pt"]},
	{"c": 0, "w": 731 , "p": "padding-top", "t":"padding-top", "d": "CSS 1 property. Specifies the amount of padding at the top of an element", "m": ["002b"], "s": ["hb"]},
	{"c": 0, "w": 911 , "p": "text-shadow", "t":"text-shadow", "d": "CSS 2 property. Defines the depth, blur, and color for a drop-shadow for text content", "m": ["002b"], "s": ["pp"]},
	{"c": 0, "w": 435 , "p": "border-style", "t": "border-style", "d": "CSS 1 property. Specifies a style for a border", "m": ["002b"], "s": ["hb"]}
]


const app = new App({
	target: document.body,
	props: {
		name: 'world',
		pics: pics
	}
});

export default app;